[build]
  publish = "public/"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "24"

[[redirects]]
  from = "/assets/*"
  to = "https://downloads.ctfassets.net/:splat"
  status = 200

[[redirects]]
  from = "/podcasts/*"
  to = "https://saladcast.s3-eu-west-1.amazonaws.com/:splat"
  status = 200

[[redirects]]
  from = "/feed"
  to = "/rss.xml"

[[redirects]]
  from = "/archives/category/saladcast/feed"
  to = "/saladcast.xml"
  